### ISSUE TITLE
Global-buffer-overflow on Punch-Out!!

### ISSUE THREAD

**Issue by luctrudeau** [sroby/f-type#12]
```
./f-type ../../Downloads/Mike\ Tyson\'s\ Punch-Out!!\ \(U\)\ \(PRG\ 1\)\ \[h1\].nes 
PRG ROM: 128KB
CHR ROM: 128KB
Mapper: 9 (Nintendo PxROM (MMC2))
Mirroring: Horizontal
Battery-backed SRAM: No
No controllers were found, will continue without input
=================================================================
==22798==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000004e6e3c at pc 0x0000004cdf9f bp 0x7fffffcbad30 sp 0x7fffffcbad20
READ of size 4 at 0x0000004e6e3c thread T0
    #0 0x4cdf9e in task_render_pixel src/ppu.c:102
    #1 0x4cdf9e in ppu_step src/ppu.c:318
    #2 0x4c9fde in machine_advance_frame src/machine.c:56
    #3 0x4cf2b0 in window_loop src/window.c:240
    #4 0x406491 in main src/main.c:111
    #5 0x7ffff6dce82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x406618 in _start (/home/ltrudeau/Workspace/f-type/f-type+0x406618)

0x0000004e6e3c is located 59 bytes to the right of global variable '*.LC2' defined in 'src/window.c' (0x4e6de0) of size 33
  '*.LC2' is ascii string 'Assigned "%s" as controller #%d
'
0x0000004e6e3c is located 4 bytes to the left of global variable '*.LC3' defined in 'src/window.c' (0x4e6e40) of size 5
  '*.LC3' is ascii string 'best'
SUMMARY: AddressSanitizer: global-buffer-overflow src/ppu.c:102 task_render_pixel
Shadow bytes around the buggy address:
  0x000080094d70: 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9
  0x000080094d80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080094d90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080094da0: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080094db0: 00 00 00 00 00 00 07 f9 f9 f9 f9 f9 00 00 00 00
=>0x000080094dc0: 01 f9 f9 f9 f9 f9 f9[f9]05 f9 f9 f9 f9 f9 f9 f9
  0x000080094dd0: 00 00 00 01 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x000080094de0: 00 00 07 f9 f9 f9 f9 f9 00 00 f9 f9 f9 f9 f9 f9
  0x000080094df0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080094e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080094e10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe

```

**Comment by sroby** [comment]
Fixed in master
